### ISSUE TITLE
Exciting to see this using MyST!

### ISSUE THREAD

**Issue by rowanc1** [leouieda/nene#30]
I know a few other folks looking to make static scientific blogs, so this coming together with some of the underlying movements in the myst/jupyterBook space is really fantastic. :)

Are there things that MyST is missing when you are approaching it from this angle? Or things you wish it did better?

We are going through some serious improvements to the underlying stack/spec at the moment (e.g. [myst-spec](https://github.com/executablebooks/myst-spec)), so any feedback you have would be helpful input!

**Comment by rowanc1** [comment]
Oh, looking through the commits more, it looks like you went the other way, now I want feedback even more. :)

**Comment by leouieda** [comment]
😆 

Well, I originally tried MyST to get things like directives for admonitions, etc. But then realized that it only supported those through docutils. It was really hard to find the HTML renderer in the docs but I got it working as a normal commonmark render and that was fine for what I needed. But as I dug a bit deeper and started thinking about things like syntax highlighting code blocks, I saw that MyST was based on markdown-it-py but added some sphinx/docutils specific things. So I decided to go down a level and call markdown-it-py directly since it was clearer to me how to achieve that through it. 

I'm not using any of the fancy cross-referencing, etc. Particularly since that is probably handled by sphinx and not MyST right? For a site generator like this, I don't need that really and I'm not hoping to replicate sphinx. 

But the MyST spec looks interesting. If there is a more standardized HTML output with directives etc that's supported in the Python parser, I'll definitely look to going back to it. It shouldn't be hard to switch between the two.
